### ISSUE TITLE
Random Addon 

### ISSUE THREAD

**Issue by multiaudacity** [everyday-as/pivity-issues#1308] opened 2024-08-16 12:00 UTC
### Feature

A feature similar to I'm feeling lucky on google where you can set potential filters (for supported and unsupported add-ons as well as owned potentially) to randomly select an addon on the site and direct you to the page. Could potentially help find "new" add-ons that you wouldn't have seen normally see via doom scrolling through the pages

**Comment by TheodoorP** [comment] 2024-08-16 12:03
Duplicate of #996

**Closed as not planned by TheodoorP** 2024-08-16 12:03 UTC
Labels: 🌟 Feature
