### ISSUE TITLE
Wrong display when someone buys an addon for someone else from the content creator perspective

### ISSUE THREAD

**Issue by Akulla-A** [everyday-as/pivity-issues#1252] opened 2023-03-18 11:45 UTC
### Expected Behavior

When someone buys an addon for somebody else, the notification display shows something like:
BUYER purchased blablabla for RECEIVER

### Actual Behavior

When someone buys an addon for somebody else, the notification display shows something like:
RECEIVER purchased blablabla for RECEIVER

### Reproduction Steps

```markdown
Did nothing special
```

### Browsers

Brave 1.49.120

### Example URL

https://www.gmodstore.com/notifications

### GmodStore Version

v13.1.6

### Additional Information

![Capture d’écran 2023-03-18 114221](https://user-images.githubusercontent.com/73881726/226103477-b42884f1-7afb-431d-9d77-12bd9616e53d.png)
![Capture d’écran 2023-03-18 114209](https://user-images.githubusercontent.com/73881726/226103480-6daf72a1-bc76-4a47-95ca-bfda4e0c7e9f.png)

**Comment by TheodoorP** [comment] 2023-06-29 17:23
Technically speaking, this is intended behaviour, as the user that bought the addon is the purchaser, not the receiver.

**Comment by JoshPiper** [comment] 2023-06-30 18:36
> Technically speaking, this is intended behaviour, as the user that bought the addon is the purchaser, not the receiver.

That's the expected behaviour, but not the actual behaviour it seems?

Alice buys an addon for Bob, the message should be "Alice bought ADDON for Bob", whereas it's currently "Bob bought ADDON for Bob".

**Comment by TheodoorP** [comment] 2024-08-15 20:34
Fixed in the next release.

**Closed by TheodoorP** 2024-08-15 20:34 UTC
Labels: 🐞 Bug
