### ISSUE TITLE
Icon Overlay for Announcements blocks click.

### ISSUE THREAD

**Issue by JoshPiper** [everyday-as/pivity-issues#1311] opened 2024-08-18 15:09 UTC
### Expected Behavior

`fal fa-megaphone fa-10x fa-fw` is overlayed over the text and links for `card-body flex flex-col justify-center position-relative`, so you can't click on the "Read More" button or author name.

### Actual Behavior

It should be underlayed.

### Reproduction Steps

```markdown
-
```

### Browsers

Chrome Latest

### Example URL

https://www.gmodstore.com/market/view/rogue-scoreboard

**Comment by TheodoorP** [comment] 2024-08-18 15:09
Duplicate of #1294

**Closed as completed by TheodoorP** 2024-08-18 15:09 UTC
Labels: 🐞 Bug
